FROM python:3.10-alpine
WORKDIR /api
COPY flask_api/requirements.txt flask_api/server.py flask_api/wsgi.py  .
RUN pip install -r requirements.txt

ENV FLASK_ENV development
ENV FLASK_RUN_PORT 5001
EXPOSE 5001

CMD ["gunicorn", "wsgi:app", "-w 2", "-b 0.0.0.0:5001", "-t 30"]
